spring:
  application:
    name: shift-scheduling-calculate-service
  # 设置不参与热部署的文件或文件夹
  devtools:
    restart:
      # 不需要热部署的文件，修改这些建议重启项目
      exclude: static/**,public/**,config/application.yml
      # 打开热部署开关
      enabled: true
      additional-paths: src/main/java
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cache:
    type: redis
    redis:
      time-to-live: 86400000 #过期时间毫秒（设置一天）
      #      key-prefix: CACHE_ #设置缓存的前缀
      #      use-key-prefix: true #不开启默认使用分区的名称为前缀
      cache-null-values: true #是否缓存空值，解决缓存击穿问题
  profiles:
    # 启动项目所使用的环境
    #    active: prod
    #    active: dev
    active: dam

#hystrix的超时时间，调用远程服务的可接受时间，设置太短的话，调用远程服务很容易报超时异常
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
#多线程配置
sss:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
