server:
  port: 6002
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_scheduling_system?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        # 开启消息手动确认机制（手动Ack），避免消息自动确认而丢失
        acknowledge-mode: manual
  redis:
    host: 127.0.0.1
    port: 6379
    password: daDShdasS2132..
    database: 0
    timeout: 1800000
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
  #  zipkin:
  #    base-url: http://127.0.0.1:9411/
  #    discovery-client-enabled: false
  #    sender:
  #      type: web
  #  sleuth:
  #    sampler:
  #      probability: 1
  logging:
    level:
      org:
        springframework:
          cloud:
            openfeign: debug
            # 链路最终控制台输出
            sleuth: debug
